# Generated by Django 5.2.1 on 2025-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hip',
            field=models.FloatField(blank=True, help_text='Vòng mông (cm, chỉ dùng cho nữ)', null=True),
        ),
    ]
