# Generated by Django 5.2.1 on 2025-05-24 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_birthdate_userprofile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('low', 'Giảm mỡ'), ('medium', 'Duy trì'), ('high', 'Tăng cơ')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('any', 'Mọi giới')], default='any', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=50)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.CharField(max_length=50)),
                ('rest', models.PositiveIntegerField(help_text='Thời gian nghỉ giữa các set (giây)')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workoutplan')),
            ],
        ),
    ]
