[build]
root = "foodpro_backend"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"

[start]
command = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn foodpro_backend.wsgi:application --bind 0.0.0.0:$PORT"
