# Generated by Django 5.2.1 on 2025-05-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_gender_userprofile_hip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Chỉ số BMI', null=True),
        ),
    ]
